### ISSUE TITLE
Creating new projects with this sample gets compiled with the same SHA1 keys as other projects

### ISSUE THREAD

**Issue by Jarrio** [haxe-react/haxe-react-native-sample#2]
When you're using authentication with an app (like google signin) and utilising a service like `Firebase` you're required to provide a `sha1` key which is generated from the android folder from `keytool` or from android studio.

The problem is I have 2 projects which I want to use OAuth in and the firebase api but because I'm using the same base project it seems to be resulting in the same sha1 key for each new project which results in a conflict error for OAuth.

Is there a way to regenerate this key?

**Comment by kevinresol** [comment]
I am not sure about this. But if I were you I would try to look if the two android apps are having the same name/package.

**Comment by Jarrio** [comment]
I apologise for the late reply, you are right. I had thought the package name should have been `com.example` and it would automatically append the application name to that string. It appears like that was completely wrong and I should do `com.example.name`. Thanks!
